### PR TITLE
change password even if email is admin@example.com

### PR DESCRIPTION
**Pull request by qq7**

### CODE REVIEW

**Comment by JedMeister** [comment]
Not sure about this one TBH.

Other than for testing, would anyone really want to set the admin email to be `admin@example.com`?

And even for testing, IMO it's beneficial to test an alternate email. That's because the default email (where required) is usually set to `admin@example.com` at build time. Before I started changing it for testing (FWIW I usually change it to `admin@example.org`) there were a couple of appliances/inithooks that slipped through which wouldn't update the email address! (I.e. it remained set as `admin@example.com` even after setting it to something different via the inithooks).

What might perhaps be useful, is checking the DB for the email and updating the password of that account (if it exists already)? That might make the inithook more useful for users beyond firstboot? Then if it is re-run by the user it could be used to reset the password of an existing account.

Having said all that though, it's not a priority at all. There are other issues/ideas that are probably of much higher priority. Even if we were to consider doing that, I'd prefer that we looked broadly across the library and implemented it on all relevant appliances. I.e. it'd want to be a planned update and roll-out. There are also many appliances that include an email which aren't being updated (I'm pretty syre that it's mostly the appliances that use email as a login username that update it).

PS I'm happy to discuss further and change my mind if you have a good rationale that I'm not seeing.

**Comment by qq7** [comment]
I got your point. Sahana-Eden won't allow you to update email if you're trying to change it to what was already there. I think the best way to do this would be to change the inithook to be two separate shell queries.

**Comment by JedMeister** [comment]
Looking at this again, you're probably right and it should update the password, regardless of the email that is set... I'll leave this unmerged for now, but will merge it soon...

**Comment by OnGle** [comment]
Interestingly enough, I believe I hit this issue again during testing, however the issue (afaik) appears to not be setting it to it's previous value, but rather having multiple users with the same email address. 

Previously, at some point in time I assume `user_id = 1` was the administrator account but now it's a user account, the admin account is now `user_id = 2`. So when the inithook sets the user account's email address to `admin@example.com` it clashes with the default administrators email causing it to fail.

**Pull request closed without merging**
